console.log(5)
console.log(5n)
console.log("5")
console.log(true)
console.log(undefined)
console.log(null)
console.log({thing1:5,thing2:3})
console.log(typeof 5)
console.log(typeof 5n)
console.log(typeof "5")
console.log(typeof true)
console.log(typeof undefined)
console.log(typeof null)
console.log(typeof {thing1:5,thing2:3}) 
